version: "3.1"
services:
  shock:
    image: kbase/kb_shock:${TRAVIS_BRANCH:-latest}
    command:
      - "-template"
      - "/kb/deployment/conf/.templates/shock-server.cfg.templ:/kb/deployment/conf/shock-server.cfg"
      - "/kb/deployment/bin/shock-server"
      - "--conf"
      - "/kb/deployment/conf/shock-server.cfg"
    ports:
      - "7044:7044"
  mongoinit:
    image: mongo:2
    volumes:
      - ./shock.mongodump:/mnt/shock.mongodump
    entrypoint: [ "mongorestore", "--host", "mongo", "/mnt/shock.mongodump"]
    depends_on: [ "mongo" ]
  mongo:
    image: mongo:2
    ports:
      - "27017:27017"
secrets:
  auth_data:
    file: ./secrets/auth_data
  auth_template:
    file: ./secrets/auth_template